[package]
name = "rust_space_trading"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
nalgebra = "0.32.5"
num-bigint = "0.4.5"
ratatui = "0.26.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

[features]
radius = []
azerty = []
