[tree]
select_next = "down"
select_previous = "up"
zoom_in = "+"
zoom_out = "-"
toggle_expand = "space"
map_offset_up = "w"
map_offset_down = "s"
map_offset_left = "a"
map_offset_right = "d"
map_offset_reset = "0"
enter_search = "/"
focus = "f"
autoscale = "x"
quit = "esc"
speed_up = ">"
slow_down = "<"
toggle_time = "t"
toggle_info = "i"

[search]
move_cursor_right = "right"
move_cursor_left = "left"
select_next = "down"
select_previous = "up"
leave_search = "esc"
validate_search = "enter"
delete_char = "backspace"

[info]
leave_info = "i"
